export const menuData = [
  {
    category: "Soft Drinks Items",
    products: [
      { id: 1, name: "7 Up", price: 12.03 },
      { id: 2, name: "Apple Juice", price: 22.4 },
      { id: 3, name: "Mango Juice", price: 10.0 },
      { id: 31, name: "Coca Cola", price: 12.03 },
      { id: 32, name: "Orange Juice", price: 15.0 },
      { id: 33, name: "Sprite", price: 12.03 },
      { id: 34, name: "Buttermilk", price: 8.0 },
    ],
  },
  {
    category: "Lunch Items",
    products: [
      { id: 4, name: "Mysore masala dosa", price: 1000.70 },
      { id: 5, name: "Curd Rice", price: 40.0 },
      { id: 6, name: "Biriyani", price: 120.0 },
      { id: 35, name: "Dal Makhani", price: 80.0 },
      { id: 36, name: "Pulao", price: 90.0 },
      { id: 37, name: "Fish Curry", price: 140.0 },
      { id: 38, name: "Paneer Butter Masala", price: 110.0 },
      { id: 55, name: "Chicken Curry", price: 130.0 },
      { id: 56, name: "Mutton Rogan Josh", price: 160.0 },
      { id: 57, name: "Malai Kofta", price: 100.0 },
      { id: 58, name: "Palak Paneer", price: 95.0 },
      { id: 59, name: "Chana Masala", price: 85.0 },
      { id: 60, name: "Rajma Chawal", price: 90.0 },
      { id: 61, name: "Kadai Paneer", price: 110.0 },
      { id: 62, name: "Butter Chicken", price: 140.0 },
      { id: 63, name: "Vegetable Korma", price: 95.0 },
      { id: 64, name: "Prawn Curry", price: 150.0 },
      { id: 65, name: "Mushroom Masala", price: 90.0 },
      { id: 66, name: "Egg Curry", price: 80.0 },
      { id: 67, name: "Mixed Veg Curry", price: 85.0 },
      { id: 68, name: "Bhindi Masala", price: 75.0 },
      { id: 69, name: "Aloo Gobi", price: 70.0 },
      { id: 70, name: "Chicken Biryani", price: 130.0 },
      { id: 71, name: "Veg Biryani", price: 100.0 },
      { id: 72, name: "Fish Biryani", price: 140.0 },
      { id: 73, name: "Mutton Biryani", price: 160.0 },
      { id: 74, name: "Jeera Rice", price: 60.0 },
      { id: 75, name: "Dal Tadka", price: 70.0 },
      { id: 76, name: "Chicken Tikka Masala", price: 130.0 },
      { id: 77, name: "Paneer Tikka Masala", price: 110.0 },
      { id: 78, name: "Veg Kolhapuri", price: 95.0 },
      { id: 79, name: "Chicken Chettinad", price: 135.0 },
      { id: 80, name: "Dal Fry", price: 65.0 },
      { id: 81, name: "Methi Malai Matar", price: 90.0 },
      { id: 82, name: "Shahi Paneer", price: 115.0 },
      { id: 83, name: "Chicken Korma", price: 130.0 },
      { id: 84, name: "Veg Jalfrezi", price: 85.0 },
      { id: 85, name: "Fish Tikka", price: 140.0 },
      { id: 86, name: "Matar Paneer", price: 95.0 },
      { id: 87, name: "Chicken Saagwala", price: 125.0 },
      { id: 88, name: "Dal Palak", price: 75.0 },
      { id: 89, name: "Veg Kofta", price: 90.0 },
      { id: 90, name: "Chicken Kadai", price: 130.0 },
      { id: 91, name: "Paneer Bhurji", price: 100.0 },
      { id: 92, name: "Mushroom Do Pyaza", price: 95.0 },
      { id: 93, name: "Chicken Handi", price: 135.0 },
      { id: 94, name: "Veg Handi", price: 95.0 }
    ],
  },
  {
    category: "Breakfast Items",
    products: [
      { id: 7, name: "Idli", price: 20.0 },
      { id: 8, name: "Dosa", price: 30.0 },
      { id: 9, name: "Upma", price: 25.0 },
      { id: 39, name: "Poori", price: 35.0 },
      { id: 40, name: "Uttapam", price: 40.0 },
      { id: 41, name: "Pongal", price: 35.0 },
      { id: 42, name: "Medu Vada", price: 25.0 },
      { id: 43, name: "Rava Dosa", price: 35.0 },
    ],
  },
  {
    category: "Desserts",
    products: [
      { id: 10, name: "Gulab Jamun", price: 15.0 },
      { id: 11, name: "Rasmalai", price: 30.0 },
      { id: 12, name: "Ice Cream", price: 35.0 },
      { id: 44, name: "Kheer", price: 40.0 },
      { id: 45, name: "Jalebi", price: 25.0 },
      { id: 46, name: "Kulfi", price: 35.0 },
      { id: 47, name: "Gajar Ka Halwa", price: 45.0 },
    ],
  },
  {
    category: "Snacks",
    products: [
      { id: 13, name: "Samosa", price: 12.0 },
      { id: 14, name: "Vada", price: 10.0 },
      { id: 15, name: "Paneer Roll", price: 45.0 },
      { id: 48, name: "Bhel Puri", price: 30.0 },
      { id: 49, name: "Pani Puri", price: 25.0 },
      { id: 50, name: "Pakora", price: 20.0 },
      { id: 51, name: "Kachori", price: 15.0 },
      { id: 52, name: "Dhokla", price: 30.0 },
    ],
  },
  {
    category: "Hot Beverages",
    products: [
      { id: 16, name: "Masala Chai", price: 15.0 },
      { id: 17, name: "Filter Coffee", price: 18.0 },
      { id: 18, name: "Green Tea", price: 20.0 },
      { id: 53, name: "Hot Chocolate", price: 25.0 },
      { id: 54, name: "Lemon Tea", price: 15.0 },
      { id: 55, name: "Herbal Tea", price: 22.0 },
    ],
  },
  {
    category: "Chinese Items",
    products: [
      { id: 19, name: "Fried Rice", price: 70.0 },
      { id: 20, name: "Hakka Noodles", price: 75.0 },
      { id: 21, name: "Manchurian", price: 90.0 },
      { id: 56, name: "Chow Mein", price: 80.0 },
      { id: 57, name: "Spring Rolls", price: 45.0 },
      { id: 58, name: "Kung Pao Chicken", price: 95.0 },
      { id: 59, name: "Sweet and Sour Soup", price: 60.0 },
    ],
  },
  {
    category: "Tandoori Specials",
    products: [
      { id: 22, name: "Tandoori Chicken", price: 160.0 },
      { id: 23, name: "Paneer Tikka", price: 100.0 },
      { id: 24, name: "Tandoori Roti", price: 15.0 },
      { id: 60, name: "Seekh Kebab", price: 140.0 },
      { id: 61, name: "Fish Tikka", price: 180.0 },
      { id: 62, name: "Malai Tikka", price: 150.0 },
      { id: 63, name: "Tandoori Mushroom", price: 90.0 },
    ],
  },
  {
    category: "South Indian Combos",
    products: [
      { id: 25, name: "Mini Tiffin", price: 60.0 },
      { id: 26, name: "Meals", price: 90.0 },
      { id: 27, name: "Pongal Vada", price: 50.0 },
      { id: 64, name: "Dosa Platter", price: 85.0 },
      { id: 65, name: "Idli Sambar", price: 55.0 },
      { id: 66, name: "Rava Meal", price: 75.0 },
    ],
  },
  {
    category: "North Indian Thali",
    products: [
      { id: 28, name: "Rajma Chawal", price: 55.0 },
      { id: 29, name: "Chole Bhature", price: 65.0 },
      { id: 30, name: "Aloo Paratha", price: 45.0 },
      { id: 67, name: "Dal Tadka", price: 50.0 },
      { id: 68, name: "Paneer Thali", price: 120.0 },
      { id: 69, name: "Veg Thali", price: 100.0 },
      { id: 70, name: "Non-Veg Thali", price: 150.0 },
    ],
  },
  {
    category: "Salads",
    products: [
      { id: 95, name: "Greek Salad", price: 60.0 },
      { id: 96, name: "Caesar Salad", price: 70.0 },
      { id: 97, name: "Sprout Salad", price: 50.0 },
      { id: 98, name: "Fruit Salad", price: 55.0 },
    ],
  },
  {
    category: "Wraps & Rolls",
    products: [
      { id: 99, name: "Chicken Wrap", price: 80.0 },
      { id: 100, name: "Veggie Wrap", price: 70.0 },
      { id: 101, name: "Egg Roll", price: 65.0 },
      { id: 102, name: "Paneer Kathi Roll", price: 85.0 },
    ],
  },
  {
    category: "Pizzas",
    products: [
      { id: 103, name: "Margherita", price: 120.0 },
      { id: 104, name: "Farmhouse", price: 150.0 },
      { id: 105, name: "Pepperoni", price: 170.0 },
      { id: 106, name: "Veg Extravaganza", price: 160.0 },
    ],
  },
  {
    category: "Burgers",
    products: [
      { id: 107, name: "Veg Burger", price: 60.0 },
      { id: 108, name: "Cheese Burger", price: 75.0 },
      { id: 109, name: "Chicken Burger", price: 90.0 },
      { id: 110, name: "Double Patty Burger", price: 110.0 },
    ],
  },
  {
    category: "Pasta Specials",
    products: [
      { id: 111, name: "White Sauce Pasta", price: 95.0 },
      { id: 112, name: "Red Sauce Pasta", price: 90.0 },
      { id: 113, name: "Pesto Pasta", price: 100.0 },
      { id: 114, name: "Mac and Cheese", price: 85.0 },
    ],
  },
  {
    category: "Breads & Rotis",
    products: [
      { id: 115, name: "Plain Roti", price: 10.0 },
      { id: 116, name: "Butter Naan", price: 20.0 },
      { id: 117, name: "Garlic Naan", price: 25.0 },
      { id: 118, name: "Lachha Paratha", price: 30.0 },
    ],
  },
  {
    category: "Rice Specials",
    products: [
      { id: 119, name: "Steamed Rice", price: 40.0 },
      { id: 120, name: "Lemon Rice", price: 45.0 },
      { id: 121, name: "Tamarind Rice", price: 50.0 },
      { id: 122, name: "Coconut Rice", price: 55.0 },
    ],
  },
  {
    category: "Street Food",
    products: [
      { id: 123, name: "Aloo Tikki", price: 20.0 },
      { id: 124, name: "Chole Kulche", price: 50.0 },
      { id: 125, name: "Frankie Roll", price: 60.0 },
      { id: 126, name: "Dabeli", price: 25.0 },
    ],
  },
  {
    category: "Sandwiches",
    products: [
      { id: 127, name: "Veg Sandwich", price: 40.0 },
      { id: 128, name: "Grilled Cheese Sandwich", price: 55.0 },
      { id: 129, name: "Chicken Sandwich", price: 70.0 },
      { id: 130, name: "Paneer Sandwich", price: 65.0 },
    ],
  },
  {
    category: "Mocktails",
    products: [
      { id: 131, name: "Virgin Mojito", price: 45.0 },
      { id: 132, name: "Blue Lagoon", price: 50.0 },
      { id: 133, name: "Strawberry Cooler", price: 55.0 },
      { id: 134, name: "Mint Magic", price: 50.0 },
    ],
  }
  
];